// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

package robot;

public final class RobotOuterClass {
  private RobotOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * It is the scenario where the fight will take place 
   * </pre>
   *
   * Protobuf enum {@code robot.SCENARIO}
   */
  public enum SCENARIO
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CITY = 0;</code>
     */
    CITY(0),
    /**
     * <code>SPACE = 1;</code>
     */
    SPACE(1),
    /**
     * <code>MALL = 2;</code>
     */
    MALL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CITY = 0;</code>
     */
    public static final int CITY_VALUE = 0;
    /**
     * <code>SPACE = 1;</code>
     */
    public static final int SPACE_VALUE = 1;
    /**
     * <code>MALL = 2;</code>
     */
    public static final int MALL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SCENARIO valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SCENARIO forNumber(int value) {
      switch (value) {
        case 0: return CITY;
        case 1: return SPACE;
        case 2: return MALL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SCENARIO>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SCENARIO> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SCENARIO>() {
            public SCENARIO findValueByNumber(int number) {
              return SCENARIO.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return robot.RobotOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final SCENARIO[] VALUES = values();

    public static SCENARIO valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SCENARIO(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:robot.SCENARIO)
  }

  public interface RobotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:robot.Robot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *custom unique name 
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *custom unique name 
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @return A list containing the powers.
     */
    java.util.List<java.lang.String>
        getPowersList();
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @return The count of powers.
     */
    int getPowersCount();
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @param index The index of the element to return.
     * @return The powers at the given index.
     */
    java.lang.String getPowers(int index);
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the powers at the given index.
     */
    com.google.protobuf.ByteString
        getPowersBytes(int index);

    /**
     * <pre>
     *It is the robot's speed and it reforced by their attacks or powers 
     * deprecated and SHould use the attribute repeated powers 
     * </pre>
     *
     * <code>int32 speed_level = 10 [deprecated = true];</code>
     * @return The speedLevel.
     */
    @java.lang.Deprecated int getSpeedLevel();

    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     * @return Whether the helper field is set.
     */
    boolean hasHelper();
    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     * @return The helper.
     */
    robot.RobotOuterClass.Robot.Helper getHelper();
    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     */
    robot.RobotOuterClass.Robot.HelperOrBuilder getHelperOrBuilder();
  }
  /**
   * Protobuf type {@code robot.Robot}
   */
  public static final class Robot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:robot.Robot)
      RobotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Robot.newBuilder() to construct.
    private Robot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Robot() {
      id_ = "";
      name_ = "";
      powers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Robot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Robot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                powers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              powers_.add(s);
              break;
            }
            case 80: {

              speedLevel_ = input.readInt32();
              break;
            }
            case 90: {
              robot.RobotOuterClass.Robot.Helper.Builder subBuilder = null;
              if (helper_ != null) {
                subBuilder = helper_.toBuilder();
              }
              helper_ = input.readMessage(robot.RobotOuterClass.Robot.Helper.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(helper_);
                helper_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          powers_ = powers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return robot.RobotOuterClass.internal_static_robot_Robot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return robot.RobotOuterClass.internal_static_robot_Robot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              robot.RobotOuterClass.Robot.class, robot.RobotOuterClass.Robot.Builder.class);
    }

    public interface HelperOrBuilder extends
        // @@protoc_insertion_point(interface_extends:robot.Robot.Helper)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      java.lang.String getId();
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * <pre>
     *It is a robot helper who fights in hand to hand with its owner 
     * </pre>
     *
     * Protobuf type {@code robot.Robot.Helper}
     */
    public static final class Helper extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:robot.Robot.Helper)
        HelperOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Helper.newBuilder() to construct.
      private Helper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Helper() {
        id_ = "";
        name_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Helper();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Helper(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return robot.RobotOuterClass.internal_static_robot_Robot_Helper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return robot.RobotOuterClass.internal_static_robot_Robot_Helper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                robot.RobotOuterClass.Robot.Helper.class, robot.RobotOuterClass.Robot.Helper.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object id_;
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof robot.RobotOuterClass.Robot.Helper)) {
          return super.equals(obj);
        }
        robot.RobotOuterClass.Robot.Helper other = (robot.RobotOuterClass.Robot.Helper) obj;

        if (!getId()
            .equals(other.getId())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static robot.RobotOuterClass.Robot.Helper parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static robot.RobotOuterClass.Robot.Helper parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static robot.RobotOuterClass.Robot.Helper parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(robot.RobotOuterClass.Robot.Helper prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       *It is a robot helper who fights in hand to hand with its owner 
       * </pre>
       *
       * Protobuf type {@code robot.Robot.Helper}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:robot.Robot.Helper)
          robot.RobotOuterClass.Robot.HelperOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return robot.RobotOuterClass.internal_static_robot_Robot_Helper_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return robot.RobotOuterClass.internal_static_robot_Robot_Helper_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  robot.RobotOuterClass.Robot.Helper.class, robot.RobotOuterClass.Robot.Helper.Builder.class);
        }

        // Construct using robot.RobotOuterClass.Robot.Helper.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = "";

          name_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return robot.RobotOuterClass.internal_static_robot_Robot_Helper_descriptor;
        }

        @java.lang.Override
        public robot.RobotOuterClass.Robot.Helper getDefaultInstanceForType() {
          return robot.RobotOuterClass.Robot.Helper.getDefaultInstance();
        }

        @java.lang.Override
        public robot.RobotOuterClass.Robot.Helper build() {
          robot.RobotOuterClass.Robot.Helper result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public robot.RobotOuterClass.Robot.Helper buildPartial() {
          robot.RobotOuterClass.Robot.Helper result = new robot.RobotOuterClass.Robot.Helper(this);
          result.id_ = id_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof robot.RobotOuterClass.Robot.Helper) {
            return mergeFrom((robot.RobotOuterClass.Robot.Helper)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(robot.RobotOuterClass.Robot.Helper other) {
          if (other == robot.RobotOuterClass.Robot.Helper.getDefaultInstance()) return this;
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            onChanged();
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          robot.RobotOuterClass.Robot.Helper parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (robot.RobotOuterClass.Robot.Helper) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object id_ = "";
        /**
         * <code>string id = 1;</code>
         * @return The id.
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string id = 1;</code>
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>string id = 1;</code>
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          id_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:robot.Robot.Helper)
      }

      // @@protoc_insertion_point(class_scope:robot.Robot.Helper)
      private static final robot.RobotOuterClass.Robot.Helper DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new robot.RobotOuterClass.Robot.Helper();
      }

      public static robot.RobotOuterClass.Robot.Helper getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Helper>
          PARSER = new com.google.protobuf.AbstractParser<Helper>() {
        @java.lang.Override
        public Helper parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Helper(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Helper> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Helper> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public robot.RobotOuterClass.Robot.Helper getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *custom unique name 
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *custom unique name 
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POWERS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList powers_;
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @return A list containing the powers.
     */
    public com.google.protobuf.ProtocolStringList
        getPowersList() {
      return powers_;
    }
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @return The count of powers.
     */
    public int getPowersCount() {
      return powers_.size();
    }
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @param index The index of the element to return.
     * @return The powers at the given index.
     */
    public java.lang.String getPowers(int index) {
      return powers_.get(index);
    }
    /**
     * <pre>
     * laser , agile 
     * </pre>
     *
     * <code>repeated string powers = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the powers at the given index.
     */
    public com.google.protobuf.ByteString
        getPowersBytes(int index) {
      return powers_.getByteString(index);
    }

    public static final int SPEED_LEVEL_FIELD_NUMBER = 10;
    private int speedLevel_;
    /**
     * <pre>
     *It is the robot's speed and it reforced by their attacks or powers 
     * deprecated and SHould use the attribute repeated powers 
     * </pre>
     *
     * <code>int32 speed_level = 10 [deprecated = true];</code>
     * @return The speedLevel.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getSpeedLevel() {
      return speedLevel_;
    }

    public static final int HELPER_FIELD_NUMBER = 11;
    private robot.RobotOuterClass.Robot.Helper helper_;
    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     * @return Whether the helper field is set.
     */
    @java.lang.Override
    public boolean hasHelper() {
      return helper_ != null;
    }
    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     * @return The helper.
     */
    @java.lang.Override
    public robot.RobotOuterClass.Robot.Helper getHelper() {
      return helper_ == null ? robot.RobotOuterClass.Robot.Helper.getDefaultInstance() : helper_;
    }
    /**
     * <code>.robot.Robot.Helper helper = 11;</code>
     */
    @java.lang.Override
    public robot.RobotOuterClass.Robot.HelperOrBuilder getHelperOrBuilder() {
      return getHelper();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < powers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, powers_.getRaw(i));
      }
      if (speedLevel_ != 0) {
        output.writeInt32(10, speedLevel_);
      }
      if (helper_ != null) {
        output.writeMessage(11, getHelper());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < powers_.size(); i++) {
          dataSize += computeStringSizeNoTag(powers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPowersList().size();
      }
      if (speedLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, speedLevel_);
      }
      if (helper_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getHelper());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof robot.RobotOuterClass.Robot)) {
        return super.equals(obj);
      }
      robot.RobotOuterClass.Robot other = (robot.RobotOuterClass.Robot) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPowersList()
          .equals(other.getPowersList())) return false;
      if (getSpeedLevel()
          != other.getSpeedLevel()) return false;
      if (hasHelper() != other.hasHelper()) return false;
      if (hasHelper()) {
        if (!getHelper()
            .equals(other.getHelper())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPowersCount() > 0) {
        hash = (37 * hash) + POWERS_FIELD_NUMBER;
        hash = (53 * hash) + getPowersList().hashCode();
      }
      hash = (37 * hash) + SPEED_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedLevel();
      if (hasHelper()) {
        hash = (37 * hash) + HELPER_FIELD_NUMBER;
        hash = (53 * hash) + getHelper().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static robot.RobotOuterClass.Robot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robot.RobotOuterClass.Robot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static robot.RobotOuterClass.Robot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static robot.RobotOuterClass.Robot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static robot.RobotOuterClass.Robot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static robot.RobotOuterClass.Robot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(robot.RobotOuterClass.Robot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code robot.Robot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:robot.Robot)
        robot.RobotOuterClass.RobotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return robot.RobotOuterClass.internal_static_robot_Robot_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return robot.RobotOuterClass.internal_static_robot_Robot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                robot.RobotOuterClass.Robot.class, robot.RobotOuterClass.Robot.Builder.class);
      }

      // Construct using robot.RobotOuterClass.Robot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        powers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        speedLevel_ = 0;

        if (helperBuilder_ == null) {
          helper_ = null;
        } else {
          helper_ = null;
          helperBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return robot.RobotOuterClass.internal_static_robot_Robot_descriptor;
      }

      @java.lang.Override
      public robot.RobotOuterClass.Robot getDefaultInstanceForType() {
        return robot.RobotOuterClass.Robot.getDefaultInstance();
      }

      @java.lang.Override
      public robot.RobotOuterClass.Robot build() {
        robot.RobotOuterClass.Robot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public robot.RobotOuterClass.Robot buildPartial() {
        robot.RobotOuterClass.Robot result = new robot.RobotOuterClass.Robot(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000001) != 0)) {
          powers_ = powers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.powers_ = powers_;
        result.speedLevel_ = speedLevel_;
        if (helperBuilder_ == null) {
          result.helper_ = helper_;
        } else {
          result.helper_ = helperBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof robot.RobotOuterClass.Robot) {
          return mergeFrom((robot.RobotOuterClass.Robot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(robot.RobotOuterClass.Robot other) {
        if (other == robot.RobotOuterClass.Robot.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.powers_.isEmpty()) {
          if (powers_.isEmpty()) {
            powers_ = other.powers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePowersIsMutable();
            powers_.addAll(other.powers_);
          }
          onChanged();
        }
        if (other.getSpeedLevel() != 0) {
          setSpeedLevel(other.getSpeedLevel());
        }
        if (other.hasHelper()) {
          mergeHelper(other.getHelper());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        robot.RobotOuterClass.Robot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (robot.RobotOuterClass.Robot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *custom unique name 
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *custom unique name 
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *custom unique name 
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *custom unique name 
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *custom unique name 
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList powers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePowersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          powers_ = new com.google.protobuf.LazyStringArrayList(powers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @return A list containing the powers.
       */
      public com.google.protobuf.ProtocolStringList
          getPowersList() {
        return powers_.getUnmodifiableView();
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @return The count of powers.
       */
      public int getPowersCount() {
        return powers_.size();
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param index The index of the element to return.
       * @return The powers at the given index.
       */
      public java.lang.String getPowers(int index) {
        return powers_.get(index);
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the powers at the given index.
       */
      public com.google.protobuf.ByteString
          getPowersBytes(int index) {
        return powers_.getByteString(index);
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param index The index to set the value at.
       * @param value The powers to set.
       * @return This builder for chaining.
       */
      public Builder setPowers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePowersIsMutable();
        powers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param value The powers to add.
       * @return This builder for chaining.
       */
      public Builder addPowers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePowersIsMutable();
        powers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param values The powers to add.
       * @return This builder for chaining.
       */
      public Builder addAllPowers(
          java.lang.Iterable<java.lang.String> values) {
        ensurePowersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, powers_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPowers() {
        powers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * laser , agile 
       * </pre>
       *
       * <code>repeated string powers = 3;</code>
       * @param value The bytes of the powers to add.
       * @return This builder for chaining.
       */
      public Builder addPowersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePowersIsMutable();
        powers_.add(value);
        onChanged();
        return this;
      }

      private int speedLevel_ ;
      /**
       * <pre>
       *It is the robot's speed and it reforced by their attacks or powers 
       * deprecated and SHould use the attribute repeated powers 
       * </pre>
       *
       * <code>int32 speed_level = 10 [deprecated = true];</code>
       * @return The speedLevel.
       */
      @java.lang.Override
      @java.lang.Deprecated public int getSpeedLevel() {
        return speedLevel_;
      }
      /**
       * <pre>
       *It is the robot's speed and it reforced by their attacks or powers 
       * deprecated and SHould use the attribute repeated powers 
       * </pre>
       *
       * <code>int32 speed_level = 10 [deprecated = true];</code>
       * @param value The speedLevel to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setSpeedLevel(int value) {
        
        speedLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *It is the robot's speed and it reforced by their attacks or powers 
       * deprecated and SHould use the attribute repeated powers 
       * </pre>
       *
       * <code>int32 speed_level = 10 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearSpeedLevel() {
        
        speedLevel_ = 0;
        onChanged();
        return this;
      }

      private robot.RobotOuterClass.Robot.Helper helper_;
      private com.google.protobuf.SingleFieldBuilderV3<
          robot.RobotOuterClass.Robot.Helper, robot.RobotOuterClass.Robot.Helper.Builder, robot.RobotOuterClass.Robot.HelperOrBuilder> helperBuilder_;
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       * @return Whether the helper field is set.
       */
      public boolean hasHelper() {
        return helperBuilder_ != null || helper_ != null;
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       * @return The helper.
       */
      public robot.RobotOuterClass.Robot.Helper getHelper() {
        if (helperBuilder_ == null) {
          return helper_ == null ? robot.RobotOuterClass.Robot.Helper.getDefaultInstance() : helper_;
        } else {
          return helperBuilder_.getMessage();
        }
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public Builder setHelper(robot.RobotOuterClass.Robot.Helper value) {
        if (helperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          helper_ = value;
          onChanged();
        } else {
          helperBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public Builder setHelper(
          robot.RobotOuterClass.Robot.Helper.Builder builderForValue) {
        if (helperBuilder_ == null) {
          helper_ = builderForValue.build();
          onChanged();
        } else {
          helperBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public Builder mergeHelper(robot.RobotOuterClass.Robot.Helper value) {
        if (helperBuilder_ == null) {
          if (helper_ != null) {
            helper_ =
              robot.RobotOuterClass.Robot.Helper.newBuilder(helper_).mergeFrom(value).buildPartial();
          } else {
            helper_ = value;
          }
          onChanged();
        } else {
          helperBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public Builder clearHelper() {
        if (helperBuilder_ == null) {
          helper_ = null;
          onChanged();
        } else {
          helper_ = null;
          helperBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public robot.RobotOuterClass.Robot.Helper.Builder getHelperBuilder() {
        
        onChanged();
        return getHelperFieldBuilder().getBuilder();
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      public robot.RobotOuterClass.Robot.HelperOrBuilder getHelperOrBuilder() {
        if (helperBuilder_ != null) {
          return helperBuilder_.getMessageOrBuilder();
        } else {
          return helper_ == null ?
              robot.RobotOuterClass.Robot.Helper.getDefaultInstance() : helper_;
        }
      }
      /**
       * <code>.robot.Robot.Helper helper = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          robot.RobotOuterClass.Robot.Helper, robot.RobotOuterClass.Robot.Helper.Builder, robot.RobotOuterClass.Robot.HelperOrBuilder> 
          getHelperFieldBuilder() {
        if (helperBuilder_ == null) {
          helperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              robot.RobotOuterClass.Robot.Helper, robot.RobotOuterClass.Robot.Helper.Builder, robot.RobotOuterClass.Robot.HelperOrBuilder>(
                  getHelper(),
                  getParentForChildren(),
                  isClean());
          helper_ = null;
        }
        return helperBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:robot.Robot)
    }

    // @@protoc_insertion_point(class_scope:robot.Robot)
    private static final robot.RobotOuterClass.Robot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new robot.RobotOuterClass.Robot();
    }

    public static robot.RobotOuterClass.Robot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Robot>
        PARSER = new com.google.protobuf.AbstractParser<Robot>() {
      @java.lang.Override
      public Robot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Robot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Robot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Robot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public robot.RobotOuterClass.Robot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robot_Robot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robot_Robot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_robot_Robot_Helper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_robot_Robot_Helper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013robot.proto\022\005robot\"\255\001\n\005Robot\022\n\n\002id\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006powers\030\003 \003(\t\022\027\n\013spee" +
      "d_level\030\n \001(\005B\002\030\001\022#\n\006helper\030\013 \001(\0132\023.robo" +
      "t.Robot.Helper\032\"\n\006Helper\022\n\n\002id\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\tJ\004\010\005\020\006J\004\010\006\020\007R\005laserR\005agile*)\n\010" +
      "SCENARIO\022\010\n\004CITY\020\000\022\t\n\005SPACE\020\001\022\010\n\004MALL\020\002b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_robot_Robot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_robot_Robot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robot_Robot_descriptor,
        new java.lang.String[] { "Id", "Name", "Powers", "SpeedLevel", "Helper", });
    internal_static_robot_Robot_Helper_descriptor =
      internal_static_robot_Robot_descriptor.getNestedTypes().get(0);
    internal_static_robot_Robot_Helper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_robot_Robot_Helper_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
